name: "Release Note"
author: "Kungfu Trader"
description: "Output Release Note When Merged"
inputs:
  token:
    description: "secrets.GITHUB_TOKEN"
    required: true
  apiKey:
    description: "secrets.AIRTABLE_API_KEY"
    required: false
  bucket-prebuilt:
    description: "S3 Bucket used as release area of prebuilt binaries"
    required: false
  bucket-release:
    description: "S3 Bucket used as release area of prebuilt binaries"
    required: false
  airtable-baseid:
    description: "airtable base for pr issues"
    default: 'appAdi5zFFEsCzmEM'
    required: false
  airtable-tableid:
    description: "airtable table for pr issues"
    default: 'tblJabUQUuS6ywW5Z'
    required: false
  full-dose:
    default: false
    required: false
outputs:
  has_notes:
    description: "Whether the notes exists or not."

runs:
  using: "node16"
  main: "dist/index.js"
