name: Rob All Release Notes 
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'artifact_name'
        required: true
        default: 'kungfu'
        type: string
      artifact:
        description: 'artifact_version'
        required: true
        default: 'artifact-kungfu'
        type: string
      bucket-release-ci:
        default: "kungfu-prebuilt"
        type: string
        required: false
      aws-user-region:
        default: "cn-northwest-1"
        type: string
        required: false

jobs:
  release-note:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Crendentials (User)
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-user-region }}

      - name: Create Release Note
        continue-on-error: true
        uses: kungfu-trader/action-release-note@v1.0-alpha
        with:
            token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
            apiKey: ${{ secrets.AIRTABLE_API_KEY }}
            full-dose-repo: ${{ inputs.repo }}
            full-dose-artifact: ${{ inputs.artifact }}

      - name: Convert Release Note To Pdf
        continue-on-error: true
        uses: baileyjm02/markdown-to-pdf@v1
        with:
            input_dir: notes
            output_dir: pdfs
            build_html: true
  
      - name: Publish Release Note To AWS
        continue-on-error: true
        uses: kungfu-trader/action-release-note@v1.0-alpha
        with:
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
          apiKey: ${{ secrets.AIRTABLE_API_KEY }}
          bucket-release: ${{ inputs.bucket-release-ci }}
          full-dose-repo: ${{ inputs.repo }}
          full-dose-artifact: ${{ inputs.artifact }}
  
      - name: Upload Release Note
        uses: actions/upload-artifact@v3
        with:
            name: Release-Note-${{github.repository.name}}-${{github.sha}}
            path: |
              notes/*
              pdfs/*
            if-no-files-found: ignore
